[workspace]
authors = ["deepthought <deepthough@postech.ac.kr>"]
channels = ["conda-forge"]
name = "datavisguide"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
quarto = ">=1.8.27,<2"
r-base = ">=4.5.2,<4.6"
r-essentials = ">=4.5,<5"
r-reticulate = ">=1.44.1,<2"
